spring.application.name=autoops-backend


jwt.secret=autoops-secret-key-change-later-1234567890
jwt.expiration-millis=3600000


spring.datasource.url=jdbc:postgresql://localhost:5432/autoops_db
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.default_schema=autoops
spring.jpa.properties.hibernate.format_sql=true


n8n.webhook.url=http://localhost:5678/webhook/autoops/execute
n8n.internal.secret=autoops-internal-
